### ISSUE TITLE
Removing input box shadow on focus

### ISSUE THREAD

**Issue by lpellegr** [bennypowers/stripe-elements#42]
Using `--stripe-elements-box-shadow: 0;` removes the default box-shadow around the Stripe Elements input text. However, on input text focus, there is still a shadow that appears. I cannot find a way to remove it using this library. Any ideas?

**Comment by bennypowers** [comment]
Thanks for this issue!

Try this:

```css
stripe-elements {
  --stripe-elements-box-shadow: none;
}

stripe-elements[focused]::part(stripe) {
  box-shadow: none;
}
```
https://codesandbox.io/s/stripe-elements-web-component-lit-element-htq2g

We can take a PR to add a `--stripe-elements-focused-box-shadow` custom property if you can't suffice with shadow parts
