### ISSUE TITLE
Changing border color on focus or on error

### ISSUE THREAD

**Issue by lpellegr** [bennypowers/stripe-elements#43]
It seems that existing custom properties allow changing the input text border color for the base style only (with `--stripe-elements-border`) but provides no means to change the border color when the input has focus or the element is in error.

**Comment by bennypowers** [comment]
try this:
```css
stripe-elements[error] {
  --stripe-elements-border: 2px solid red;
}

stripe-elements[focused] {
  --stripe-elements-border: 2px solid blue;
}
```

https://codesandbox.io/s/stripe-elements-web-component-lit-element-99vbh
